name: Build C# GUI App

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  run-script:
      runs-on: windows-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup VSTest.console.exe
        uses: darenm/Setup-VSTest@v1.3
      
      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: 0.33.1

      - name: doxygen-install
        uses: ssciwr/doxygen-install@v1.6.0   
      
      - name: Download OpenCover
        run: |
              curl -L -o OpenCover.zip https://github.com/OpenCover/opencover/releases/download/4.7.922/OpenCover.4.7.922.zip
              mkdir OpenCover
              powershell -Command "Expand-Archive -Path OpenCover.zip -DestinationPath OpenCover"

      - name: Download ReportGenerator from Google Drive
        run: |
          $url = "https://drive.google.com/uc?export=download&id=1Muxd-qcBcHdlXdgDb_OcdUaNBGOZ3sAU"
          $output = "ReportGenerator_5.4.1.zip"
          Invoke-WebRequest -Uri $url -OutFile $output

      - name: Extract ReportGenerator
        run: |
          Expand-Archive -Path ReportGenerator_5.4.1.zip -DestinationPath ReportGenerator
     
      - name: Run CMD script
        shell: cmd
        run: |
          .\run.bat COM9 9600

      - name: Upload script results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: script-results
          path: ./artefacts
          
      - name: Upload Doxygen documentation as artifact
        uses: actions/upload-artifact@v3
        with:
          name: doxygen-documentation
          path: ./deploy/documentation/

      - name: Upload Coverage as artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-artifacts
          path: ./deploy/test_coverage/
